language: csharp
mono:
  - latest
script:    # the following commands are just examples, use whatever your build process requires
  - ls
  - msbuild /p:TargetFrameworkVersion=v4.5;Configuration=Release ./voucherify-dotNET-sdk/src/Voucherify/Voucherify.csproj
  - msbuild /p:TargetFrameworkVersion=v4.5;Configuration=Release ./voucherify-dotNET-sdk/src/Voucherify/Voucherify.Client.csproj
