language: csharp
mono:
  - latest
script:    # the following commands are just examples, use whatever your build process requires
  - msbuild /p:TargetFrameworkVersion=v4.5;Configuration=Release  ./src/Voucherify/Voucherify.csproj
  - msbuild /p:TargetFrameworkVersion=v4.5;Configuration=Release  ./src/Voucherify/Voucherify.Client.csproj
