language: csharp
mono:
  - latest
script:    # the following commands are just examples, use whatever your build process requires
  - dotnet restore
  - msbuild /p:Configuration=Release  ./src/Voucherify/Voucherify.csproj
