language: csharp
mono:
  - latest
script:    # the following commands are just examples, use whatever your build process requires
  - msbuild /p:Configuration=Release /p:Framework=net20 ./src/Voucherify/Voucherify.csproj
