language: csharp
solution: ./src/Voucherify.sln
script:    # the following commands are just examples, use whatever your build process requires
  - ./travis/build.sh
  - grep "Test Results" build.log
